export enum EModals {
  SEARCH = 'search',
  MENU = 'menu',
  CART = 'cart',
  ADDRESS = 'address',
  AUTH = 'auth',
  PRODUCT_ZOOM = 'productZoom',
  FILTERS = 'filters',
  CHECKOUT_DELIVERY = 'checkout_delivery',
  SIZE_HELPER = 'size_helper',
  PRE_AUTH = 'pre_auth',
  CART_DELETE = 'cart_delete',
  PRODUCT_LOOKS = 'product_looks',
  CART_EDIT_PRODUCT = 'cart_edit_product',
  WISHLIST_VIEW_PRODUCT = 'wishlist_view_product',
  AUTH_CTA = 'auth_cta',
  MOBILE_MENU = 'mobile_menu',
  PRODUCT_MOBILE_MODAL = 'product_mobile_modal',
  MOBILE_ACCOUNT_MENU = 'mobile_account_menu',
  DELETE_ADDRESS = 'delete_address',
  WISHLIST_DELETE = 'wishlist_delete',
}
